export CUDA_VISIBLE_DEVICES=0
model_name=Transformer
# 固定lambda参数为0
python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.125 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.125_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \


python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.25 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.25_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.375 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.375_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.5 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.5_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

# 固定lambda为0.5
python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0.5 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.125 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.125_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \


python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0.5 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.25 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.25_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0.5 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.375 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.375_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 0.5 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.5 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.5_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5

# 固定lambda为1
python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.125 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.125_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \


python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.25 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.25_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.375 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.375_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.5 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.5_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5

# lambda可学习，使用relu函数使lambda>0
python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --requires_grad \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.125 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.125_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \


python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --requires_grad \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.25 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.25_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --requires_grad \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.375 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.375_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5 

  python -u mix_run.py \
  --task_name long_term_forecast \
  --train_mode 1 \
  --_lambda 1 \
  --requires_grad \
  --imp_args_json ImpModelArgs/ETT/TimesNet_ETTh1.json \
  --mask_rate 0.5 \
  --imp_lr 0.001 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_0.5_96_96_J \
  --model $model_name \
  --data ETTh1 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --itr 1 \
  --top_k 5
